### ISSUE TITLE
OnFleet recommends using their Python wrapper.

### ISSUE THREAD

**Issue by daveherrington** [lionheart/python-onfleet#11]
I recently started using this OnFleet API wrapper, believing it was the recommended one to use.  After encountering problems with it (specifically with the undocumented recipients and tasks wrappers), I realized that OnFleet has its own wrapper that they recommend, here: https://github.com/onfleet/pyonfleet.

I recommend that you update the readme doc on this repo, redirecting OnFleet integrators to the recommended repo, to avoid confusion.

-Dave

**Comment by dlo** [comment]
Thanks for the heads up. I'll point folks there instead.
