### ISSUE TITLE
pip installs wrong "version"

### ISSUE THREAD

**Issue by andrenerd** [lionheart/python-onfleet#9]
`pip install onfleet`

it downloads wrong version/code. for example onfleet.py starts with that:

```
import json
import requests

ONFLEET_API_ENDPOINT = "https://onfleet.com/api/v2/"
ONFLEET_ORGANIZATION_ID = "O1o6D8OrDDMILx2YEW3YOFFg"
```

the main issue is that it contains some "bug", such as this (L126):

```
if 'worker' in obj and obj['worker'] is not None:
    task.worker = Worker.parse(obj['worker'])
```

(the problem here is that worker property is just a key (string), not a dict)

thanks

**Comment by dlo** [comment]
Just pushed up version 1.0.0 to PyPi which should fix this issue.
